name: Build and push to ghcr
on:
  push:
    branches:
      - eslint

jobs:
  ghcr:
    name: Build and push to ghcr
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/nextlab-ai/eslint
          tags: |
            type=raw,value=latest,enable=true
            type=schedule,pattern={{date 'YYYYMMDD'}}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build and push to ghcr
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
